### PR TITLE
Idva6 383 mongodb connection

### PR DESCRIPTION
**Pull request by kkonuganti-ch**
Add Mongo DB Associations document and service

### Type of change
* New feature

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by kkonuganti-ch** [comment]
not require

**Comment by kkonuganti-ch** [comment]
not required

**Pull request closed without merging**
