### PR TITLE
IDVA6-1106: Implement pagination on invites 

### PR DESCRIPTION
**Pull request by tferns-ch**
__Short description outlining key changes/additions__

Added pagination for invitations to the UserCompanyAssociations service. Updated methods to include `pageIndex` and `itemsPerPage` parameters, refactored service methods, and adjusted test cases accordingly.

Sonar - https://code-analysis.platform.aws.chdev.org/dashboard?id=uk.gov.companieshouse%3Aaccounts-association-api&pullRequest=105

__JIRA Ticket Number__

https://companieshouse.atlassian.net/browse/IDVA6-1106

### Type of change

* [ ] Bug fix
* [x] New feature
* [ ] Breaking change
* [ ] Infrastructure change

### Pull request checklist

* [x] I have added unit tests for new code that I have added
* [x] I have added/updated functional tests where appropriate
* [x] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)

__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by kkonuganti-ch — APPROVED** [review]

**Pull request merged**
